### ISSUE TITLE
How are the detection results of mAP or MissRate?

### ISSUE THREAD

**Issue by zugofn** [jas-nat/PyTorch-YOLO-V3-KAIST#3]
Thanks for your great work!
I want to ask the question that how are the result of mAP or MissRate in your experiment when you use single modal?

**Comment by jas-nat** [comment]
The mAP is about 50% for single model. I am sorry I stop working on this project. You can look up my [another repository](https://github.com/jas-nat/yolov3) for newer model

**Comment by zugofn** [comment]
Thank you for your reply,bro!
